[ryzen]
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = true
category = Custom
pulldown_type = true
EXTRACT-edge_temp,mem_temp_crit,junction_temp,junction_temp_crit,mem_temp = ^(?:[^=\n]*=){6}\+(?P<edge_temp>\d+\.\d+)[^\+\n]*\+(?P<mem_temp_crit>\d+\.\d+)(?:[^\+\n]*\+){2}(?P<junction_temp>\d+\.\d+)[^\+\n]*\+(?P<junction_temp_crit>\d+\.\d+)(?:[^=\n]*=){3}\+(?P<mem_temp>\d+\.\d+)
